name : Deploy Lambda Layer
  on :
    push :
      branches :
        -main
    jobs :
      Deploy :
        runs-on : ubuntu-latest
        steps :
        -name : checkout repository
         uses : actions/checkout
        -name : setup a pyhton libraby
         uses : action/setup-lambda@v4
         with : 
           python-version : '3.13'
        -name : Install python dependies
         run: |
          mkdir -p python
          pip install -r requirements.txt -t python
          zip -r python-layer.zip python
        -name : aws configuration
         uses : aws-actions/configure-aws-credentials@v2
           with : 
             aws-access-key-id : '${{secrets.ACCESSKEY}}'
             aws-secret-key-id : '${{secrets.SECRETKEY}}'
             aws-region : us-east-1
        -name : Deploy pyhton lambda layer
         run: |
          aws lambda update-function-code --function-name Layer-function --zip-file fileb://function.zip
          aws lambda update-function-configuration --function-name Layer-function --layers $LAYER_ARN
